export { default as Hero } from './Hero'
export { default as Services } from './Services'
export { default as About } from './About'
export { default as Features } from './Features'
export { default as Testimonial } from './Testimonial'
export { default as Projects } from './Projects'
export { default as CTA } from './CTA'
export { default as Footer } from './Footer'